name: Lakruzz - Personal blog by Lars Kruse
highlighter: pygments
exclude: [README.md]
timezone: Europe/Copenhagen
url: www.lakruzz.com
markdown: kramdown
permalink: pretty
defaults:
  -
    scope:
      type: posts
    values:
      permalink: /:categories/:title/
